[build]
  command = "pip install -r requirements.txt"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
  python_runtime = "3.11"
